name: ShortestPath

on:
  push:
    branches: [master]

jobs:
  build:
    name: ${{matrix.config.name}}
    runs-on: ${{matrix.config.os}}
    env:
      BUILD_TYPE: Release
      EXE_NAME: LinkingSearch
      INPUT_FILES: ControlFile.txt
      OUTPUT_FILES: graph-output.txt
      COMPILER: ${{matrix.config.compiler}}
      COMP: ${{matrix.config.comp}}
      CXXFLAGS: "-Werror"
    timeout-minutes: 3
    strategy:
      matrix:
        config:
          - {
              name: "Ubuntu 20.04 GCC",
              os: ubuntu-20.04,
              compiler: g++,
              comp: gcc,
              shell: 'bash {0}'
          }
    defaults:
      run:
        shell: ${{matrix.config.shell}}

    steps:
      - name: Checkout project repo from GitHub
        uses: actions/checkout@v1

      - name: Executable name Environment Variable Check
        run: |
          echo ${{env.EXE_NAME}}
          echo " "
          echo ${{runner.workspace}}
          echo " "
          echo $GITHUB_WORKSPACE
          echo " "
          $COMPILER --version
          cmake --version
          
      - name: Create build environment
        run:  mkdir ${{runner.workspace}}/build

      - name: Configure the build
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build the project
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --config $BUILD_TYPE

      - name: Test build
        working-directory: ${{runner.workspace}}/build
        run: make -j2 optimize=no debug=yes > /dev/null

      - name: List contents of build directory
        run: ls -al ${{runner.workspace}}/build

      - name: List where artifact is located
        run: ls -halt ${{runner.workspace}}/DepthFirstSearch_BreadthFirst

      - name: Run the project
        working-directory: ${{runner.workspace}}/build
        run: ./$EXE_NAME $INPUT_FILES $OUTPUT_FILES

      - name: Copy output files to artifact directory
        working-directory: ${{runner.workspace}}/DepthFirstSearch_BreadthFirst
        run: |
          mkdir artifacts
          for f in $OUTPUT_FILES
          do
            echo "  Copying $f"
            cp $f artifacts/
          done
      - name: Upload output files to GitHub so they can be reviewed
        uses: actions/upload-artifact@v1
        with:
          name: project_output
          path: ${{runner.workspace}}/DepthFirstSearch_BreadthFirst/graph-output.txt
